# Generated by Django 5.2 on 2025-06-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Administrator"), ("viewer", "Viewer")],
                default="viewer",
                max_length=10,
            ),
        ),
    ]
