# Generated by Django 5.2.1 on 2025-05-24 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveillanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Tên đợt khảo sát"),
                ),
                (
                    "total_plants",
                    models.IntegerField(verbose_name="Tổng số cây trong vườn"),
                ),
                (
                    "confidence_level",
                    models.FloatField(default=0.95, verbose_name="Độ tin cậy (0-1)"),
                ),
                (
                    "error_margin",
                    models.FloatField(
                        default=0.05, verbose_name="Biên độ sai số (0-1)"
                    ),
                ),
                (
                    "plants_to_check",
                    models.IntegerField(verbose_name="Số cây cần kiểm tra"),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Ngày khảo sát"),
                ),
                (
                    "time",
                    models.TimeField(auto_now_add=True, verbose_name="Giờ khảo sát"),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("summer", "Mùa Hè"),
                            ("autumn", "Mùa Thu"),
                            ("winter", "Mùa Đông"),
                            ("spring", "Mùa Xuân"),
                        ],
                        max_length=20,
                        verbose_name="Mùa hiện tại",
                    ),
                ),
                (
                    "pest_alert_percentage",
                    models.FloatField(verbose_name="% Cảnh báo sâu hại theo mùa"),
                ),
                (
                    "disease_alert_percentage",
                    models.FloatField(verbose_name="% Cảnh báo bệnh theo mùa"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chưa thực hiện"),
                            ("in_progress", "Đang thực hiện"),
                            ("completed", "Đã hoàn thành"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
