# Generated by Django 5.2.1 on 2025-05-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveillance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveillancesession",
            name="confidence_level",
            field=models.FloatField(
                default=0.95, verbose_name="Confidence Level (0-1)"
            ),
        ),
        migrations.AlterField(
            model_name="surveillancesession",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="Survey Date"),
        ),
        migrations.AlterField(
            model_name="surveillancesession",
            name="disease_alert_percentage",
            field=models.FloatField(verbose_name="Seasonal Disease Alert %"),
        ),
        migrations.AlterField(
            model_name="surveillancesession",
            name="error_margin",
            field=models.FloatField(default=0.05, verbose_name="Error Margin (0-1)"),
        ),
        migrations.AlterField(
            model_name="surveillancesession",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Session Name"),
        ),
        migrations.AlterField(
            model_name="surveillancesession",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="surveillancesession",
            name="pest_alert_percentage",
            field=models.FloatField(verbose_name="Seasonal Pest Alert %"),
        ),
        migrations.AlterField(
            model_name="surveillancesession",
            name="plants_to_check",
            field=models.IntegerField(verbose_name="Plants to Check"),
        ),
        migrations.AlterField(
            model_name="surveillancesession",
            name="season",
            field=models.CharField(
                choices=[
                    ("summer", "Summer"),
                    ("autumn", "Autumn"),
                    ("winter", "Winter"),
                    ("spring", "Spring"),
                ],
                max_length=20,
                verbose_name="Current Season",
            ),
        ),
        migrations.AlterField(
            model_name="surveillancesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="surveillancesession",
            name="time",
            field=models.TimeField(auto_now_add=True, verbose_name="Survey Time"),
        ),
        migrations.AlterField(
            model_name="surveillancesession",
            name="total_plants",
            field=models.IntegerField(verbose_name="Total Plants in Orchard"),
        ),
    ]
