# Generated by Django 5.2.1 on 2025-05-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveillance", "0002_alter_surveillancesession_confidence_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveillancesession",
            name="season",
            field=models.CharField(
                choices=[
                    ("wet_early", "Early Wet Season (Nov-Dec)"),
                    ("wet_peak", "Peak Wet Season (Jan-Mar)"),
                    ("dry_early", "Early Dry Season (Apr-Jun)"),
                    ("dry_peak", "Peak Dry Season (Jul-Oct)"),
                ],
                max_length=20,
                verbose_name="Current Season",
            ),
        ),
    ]
