# Generated by Django 5.2.1 on 2025-05-24 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("surveillance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveillanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(auto_now_add=True, verbose_name="Ngày hoàn thành"),
                ),
                (
                    "completion_time",
                    models.TimeField(auto_now_add=True, verbose_name="Giờ hoàn thành"),
                ),
                (
                    "plants_checked",
                    models.IntegerField(verbose_name="Số cây đã kiểm tra"),
                ),
                (
                    "plants_with_pests",
                    models.IntegerField(
                        default=0, verbose_name="Số cây phát hiện sâu hại"
                    ),
                ),
                (
                    "plants_with_diseases",
                    models.IntegerField(
                        default=0, verbose_name="Số cây phát hiện bệnh"
                    ),
                ),
                (
                    "is_orchard_healthy",
                    models.BooleanField(default=True, verbose_name="Vườn cây an toàn"),
                ),
                (
                    "recommendation",
                    models.TextField(blank=True, verbose_name="Khuyến nghị"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="surveillance.surveillancesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PestDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pest_name",
                    models.CharField(max_length=100, verbose_name="Tên sâu hại"),
                ),
                (
                    "count",
                    models.IntegerField(default=1, verbose_name="Số lượng phát hiện"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Nhẹ"),
                            ("medium", "Trung bình"),
                            ("high", "Nặng"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pest_detections",
                        to="surveillance_history.surveillancehistory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiseaseDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease_name",
                    models.CharField(max_length=100, verbose_name="Tên bệnh"),
                ),
                (
                    "count",
                    models.IntegerField(default=1, verbose_name="Số lượng phát hiện"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Nhẹ"),
                            ("medium", "Trung bình"),
                            ("high", "Nặng"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disease_detections",
                        to="surveillance_history.surveillancehistory",
                    ),
                ),
            ],
        ),
    ]
