# Generated by Django 5.2.1 on 2025-05-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveillance_history", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diseasedetection",
            name="count",
            field=models.IntegerField(default=1, verbose_name="Count"),
        ),
        migrations.AlterField(
            model_name="diseasedetection",
            name="disease_name",
            field=models.CharField(max_length=100, verbose_name="Disease Name"),
        ),
        migrations.AlterField(
            model_name="diseasedetection",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="diseasedetection",
            name="severity",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pestdetection",
            name="count",
            field=models.IntegerField(default=1, verbose_name="Count"),
        ),
        migrations.AlterField(
            model_name="pestdetection",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="pestdetection",
            name="pest_name",
            field=models.CharField(max_length=100, verbose_name="Pest Name"),
        ),
        migrations.AlterField(
            model_name="pestdetection",
            name="severity",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="surveillancehistory",
            name="completion_date",
            field=models.DateField(auto_now_add=True, verbose_name="Completion Date"),
        ),
        migrations.AlterField(
            model_name="surveillancehistory",
            name="completion_time",
            field=models.TimeField(auto_now_add=True, verbose_name="Completion Time"),
        ),
        migrations.AlterField(
            model_name="surveillancehistory",
            name="is_orchard_healthy",
            field=models.BooleanField(default=True, verbose_name="Orchard is Healthy"),
        ),
        migrations.AlterField(
            model_name="surveillancehistory",
            name="plants_checked",
            field=models.IntegerField(verbose_name="Plants Checked"),
        ),
        migrations.AlterField(
            model_name="surveillancehistory",
            name="plants_with_diseases",
            field=models.IntegerField(default=0, verbose_name="Plants with Diseases"),
        ),
        migrations.AlterField(
            model_name="surveillancehistory",
            name="plants_with_pests",
            field=models.IntegerField(default=0, verbose_name="Plants with Pests"),
        ),
        migrations.AlterField(
            model_name="surveillancehistory",
            name="recommendation",
            field=models.TextField(blank=True, verbose_name="Recommendation"),
        ),
    ]
